name: "Integration Tests"

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "SECURITY.md"
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x, 17.x, 18.x]

    name: "Integration Node v${{ matrix.node-version }}"

    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
